# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- script: |
    mvnw -DfunctionAppName=user-account-service-$(Build.SourceBranchName) clean package
  displayName: Build package

- task: AzureCLI@2
  displayName: 'Deploy app'
  inputs:
    addSpnToEnvironment: true
    failOnStandardError: true
    azureSubscription: user-account-service-hzprod-rg-access
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
        az login --service-principal -u $env:servicePrincipalId -p $env:servicePrincipalKey --tenant $env:tenantId
        New-Item -Path '.\.mvn\settings.xml' -ItemType "file" -Value '<servers><server><id>azure-auth</id><configuration><client>$env:servicePrincipalId</client><tenant>$env:tenantId</tenant><key>$env:servicePrincipalKey</key><environment>AZURE</environment></configuration></server></servers>'
        .\mvnw --settings .\.mvn\settings.xml -DfunctionAppName=user-account-service-$(Build.SourceBranchName) azure-functions:deploy